/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatWidget: typeof import('./components/common/AiChatWidget.vue')['default']
    AiPanel: typeof import('./components/common/AiPanel.vue')['default']
    CatalogItem: typeof import('./components/common/CatalogItem.vue')['default']
    CatalogItemCollapsible: typeof import('./components/common/CatalogItemCollapsible.vue')['default']
    CatalogSidebar: typeof import('./components/common/CatalogSidebar.vue')['default']
    ChapterItem: typeof import('./components/common/ChapterItem.vue')['default']
    ChapterItemCollapsible: typeof import('./components/common/ChapterItemCollapsible.vue')['default']
    CodeEditor: typeof import('./components/common/CodeEditor.vue')['default']
    CodeEditorPage: typeof import('./components/common/CodeEditorPage.vue')['default']
    CodeEditorWidget: typeof import('./components/common/CodeEditorWidget.vue')['default']
    CodePlayground: typeof import('./components/common/CodePlayground.vue')['default']
    CodePreview: typeof import('./components/common/CodePreview.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./components/common/Header.vue')['default']
    InlineCodeEditor: typeof import('./components/common/InlineCodeEditor.vue')['default']
    MonacoEditor: typeof import('./components/common/MonacoEditor.vue')['default']
    QuizModal: typeof import('./pages/misc/QuizModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/common/Sidebar.vue')['default']
  }
}
