/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatWidget: typeof import('./components/common/AiChatWidget.vue')['default']
    AiPanel: typeof import('./components/common/AiPanel.vue')['default']
    CatalogItem: typeof import('./components/common/CatalogItem.vue')['default']
    CatalogItemCollapsible: typeof import('./components/common/CatalogItemCollapsible.vue')['default']
    CatalogSidebar: typeof import('./components/common/CatalogSidebar.vue')['default']
    ChapterItem: typeof import('./components/common/ChapterItem.vue')['default']
    ChapterItemCollapsible: typeof import('./components/common/ChapterItemCollapsible.vue')['default']
    CodePlayground: typeof import('./components/common/CodePlayground.vue')['default']
    CodePreview: typeof import('./components/common/CodePreview.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    Header: typeof import('./components/common/Header.vue')['default']
    MarkdownEditor: typeof import('./components/common/MarkdownEditor.vue')['default']
    MonacoEditor: typeof import('./components/common/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/common/Sidebar.vue')['default']
  }
}
